from deletecomment import DeleteComment
from deletepost import DeletePost
from likepost import LikePost
from logout import LogOut
from mainpage import MainPage
from unlikepost import UnlikePost
from editcomment import EditComment
from editpost import EditPost
from blog import Blog
from login import Login
from newpost import NewPost
